### ISSUE TITLE
Custom client MSI missing branding logo after installation

### ISSUE THREAD

**Issue by ZetaWaves** [rustdesk/rustdesk-server-pro#238]
Custom client MSI missing branding logo after installation. The icon after installation is the default RustDesk icon, but should be the branded logo like the normal executable.

**Comment by rustdesk** [comment]
Fixed, please generate new msi.

**Comment by ZetaWaves** [comment]
This is still a problem. I did a new build, still has regular icon and now the service isn't started after installation.
